# Generated by Django 5.0.7 on 2024-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("my_first_app", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="biography",
            field=models.TextField(max_length=500),
        ),
    ]
